---
language: ruby
services:
- postgresql
before_script:
- bundle install
- psql -c "create database travis_ci_test;" -U postgres
matrix:
  include:
  - :rvm: 2.4.5
    :gemfile: gemfiles/rails_4.2.11.gemfile
  - :rvm: 2.5.3
    :gemfile: gemfiles/rails_4.2.11.gemfile
  - :rvm: 2.6.1
    :gemfile: gemfiles/rails_4.2.11.gemfile
  - :rvm: 2.4.5
    :gemfile: gemfiles/rails_5.2.2.gemfile
  - :rvm: 2.5.3
    :gemfile: gemfiles/rails_5.2.2.gemfile
  - :rvm: 2.6.1
    :gemfile: gemfiles/rails_5.2.2.gemfile
script:
- bundle exec rake spec
- bundle exec rubocop --fail-level C
